spring:
  datasource:
    url: 
    hikari:
      username: 
      password: 
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          destination: add-bonus
          group: binder-group
#        my-input:
#          destination: stream-my-topic
#          group: my-group

  #        metadata:
#          instance: c
#          haha: hehe
#          version: v1
  application:
    name: user-center
  zipkin:
    base-url: http://localhost:9411
#    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8081
logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug
#rocketmq:
#  name-server: localhost:9876
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always

jwt:
  secret: 
  expire-time-in-second: 1209600
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



