spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#         指定namespace
#         namespace: 56116141-d837-4d15-8842-94e153bb6cfb
#         NJ
#         指定集群名称
        cluster-name: BJ
#        metadata:
#          instance: c
#          haha: hehe
#          version: v1
  application:
    name: user-center

server:
  port: 8081

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always

